import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F5F5F5" },
  content: { flex: 1 },
  launch: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#F5F5F5" },
  launchLogo: { width: 180, height: 180, marginBottom: 18 },
  loadingText: { marginTop: 12, color: "#8C8C8C", fontWeight: "700" },
  authBg: { flex: 1, backgroundColor: "#F5F5F5" },
  authBgImage: { opacity: 0.08, transform: [{ scale: 1.25 }] },
  authSafe: { flex: 1 },
  authKeyboard: { flex: 1 },
  authScroll: { flexGrow: 1, justifyContent: "flex-end", padding: 20 },
  authLogo: { alignSelf: "center", width: 190, height: 170, marginBottom: 20 },
  authPanel: { borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 12, padding: 18, backgroundColor: "rgba(255,255,255,0.98)" },
  authTitle: { color: "#191919", fontSize: 25, lineHeight: 30, fontWeight: "900" },
  authCopy: { marginTop: 10, marginBottom: 18, color: "#8C8C8C", fontSize: 14, lineHeight: 21 },
  input: { height: 48, marginTop: 12, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, paddingHorizontal: 12, backgroundColor: "#FFFFFF", color: "#191919", fontWeight: "700" },
  passwordWrap: { height: 48, marginTop: 12, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, paddingLeft: 12, paddingRight: 6, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
  passwordInput: { flex: 1, height: "100%", color: "#191919", fontWeight: "700" },
  passwordToggle: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  gmailButton: { marginTop: 10, height: 48, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, backgroundColor: "#FFFFFF" },
  gmailButtonText: { color: "#191919", fontWeight: "900" },
  textButton: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  textButtonText: { color: "#FF4747", fontWeight: "900" },
  appHeader: { backgroundColor: "#FFFFFF", paddingHorizontal: 14, paddingTop: 8, paddingBottom: 8, borderBottomWidth: 1, borderColor: "#EDEDED" },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  brandLogo: { width: 36, height: 36 },
  brandTitle: { color: "#191919", fontSize: 18, fontWeight: "900" },
  brandSubtitle: { color: "#8C8C8C", fontSize: 12, fontWeight: "700" },
  homeTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 8 },
  deliveryRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 2 },
  homeBell: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EDEDED" },
  search: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 999, paddingHorizontal: 14, height: 38, backgroundColor: "#F5F5F5" },
  searchInput: { flex: 1, color: "#191919", fontWeight: "600" },
  simpleHeaderWrap: { backgroundColor: "#FFFFFF", paddingHorizontal: 14, paddingTop: 8, paddingBottom: 10, borderBottomWidth: 1, borderColor: "#EDEDED" },
  simpleHeaderTitle: { color: "#191919", fontSize: 22, fontWeight: "900" },
  simpleHeaderMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13, fontWeight: "700" },
  kicker: { color: "#8C8C8C", fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  categoryWrap: { paddingTop: 8, paddingBottom: 4, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderColor: "#EDEDED" },
  categoryList: { paddingHorizontal: 12, gap: 8, paddingBottom: 8 },
  categoryChip: { height: 34, paddingHorizontal: 14, borderRadius: 999, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E8E8E8", backgroundColor: "#FFFFFF" },
  categoryChipActive: { borderColor: "#FF4747", backgroundColor: "#FFF1F1" },
  categoryText: { color: "#595959", fontWeight: "800", fontSize: 12 },
  categoryTextActive: { color: "#FF4747" },
  emptyText: { padding: 18, color: "#8C8C8C", fontWeight: "800" },
  productList: { paddingHorizontal: 8, paddingTop: 4, paddingBottom: 24 },
  productRow: { gap: 8 },
  screenPad: { padding: 14, paddingBottom: 24 },
  emptyPanel: { alignItems: "center", justifyContent: "center", paddingVertical: 48, gap: 8 },
  emptyPanelTitle: { color: "#191919", fontSize: 20, fontWeight: "900" },
  muted: { marginTop: 8, color: "#8C8C8C", fontSize: 14, lineHeight: 20 },
  cartItemCard: { flexDirection: "row", gap: 12, marginBottom: 10, padding: 12, borderRadius: 12, backgroundColor: "#FFFFFF" },
  cartItemImage: { width: 88, height: 88, borderRadius: 10, backgroundColor: "#F0F0F0" },
  cartItemBody: { flex: 1 },
  cartItemTitle: { color: "#191919", fontSize: 14, fontWeight: "800", lineHeight: 18 },
  price: { color: "#FF4747", fontSize: 15, fontWeight: "900" },
  quantityRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  quantityButton: { width: 42, height: 42, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0DD" },
  quantityValue: { minWidth: 28, textAlign: "center", color: "#101817", fontSize: 18, fontWeight: "900" },
  panel: { borderRadius: 12, padding: 16, backgroundColor: "#FFFFFF" },
  panelTitle: { marginTop: 4, color: "#191919", fontSize: 20, fontWeight: "900" },
  metric: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderColor: "#F0F0F0", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  metricLabel: { color: "#8C8C8C", fontWeight: "700" },
  metricValue: { flexShrink: 1, textAlign: "right", color: "#191919", fontWeight: "900" },
  accentText: { color: "#FF4747" },
  primaryButton: { marginTop: 18, height: 48, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  primaryButtonSmall: { flex: 1, minHeight: 46, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  primaryButtonText: { color: "#FFFFFF", fontWeight: "900" },
  actionRow: { marginTop: 10, flexDirection: "row", gap: 10 },
  secondaryButton: { flex: 1, minHeight: 46, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF1F1" },
  secondaryButtonText: { color: "#FF4747", fontWeight: "900" },
  disabled: { opacity: 0.5 },
  accountHero: { flexDirection: "row", alignItems: "center", gap: 14, padding: 16, borderRadius: 12, backgroundColor: "#FFFFFF", marginBottom: 12 },
  accountAvatar: { width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  accountName: { color: "#191919", fontSize: 18, fontWeight: "900" },
  accountMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13, fontWeight: "700" },
  quickLinks: { gap: 10, marginBottom: 12 },
  quickLinkCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 12, backgroundColor: "#FFFFFF" },
  quickLinkCopy: { flex: 1 },
  quickLinkTitle: { color: "#191919", fontSize: 15, fontWeight: "900" },
  quickLinkMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 12, fontWeight: "700" },
  logoutButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, minHeight: 48, borderRadius: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#FFD6D6" },
  logoutButtonText: { color: "#FF4747", fontWeight: "900" },
  bottomNavWrap: { borderTopWidth: 1, borderColor: "#EDEDED", backgroundColor: "#FFFFFF" },
  bottomNav: { paddingHorizontal: 6, paddingTop: 8, paddingBottom: 4, gap: 4, alignItems: "center" },
  bottomNavItem: { minWidth: 72, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
  bottomNavIconWrap: { position: "relative" },
  bottomNavBadge: { position: "absolute", top: -6, right: -10, minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 4, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  bottomNavBadgeText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" },
  bottomNavLabel: { marginTop: 4, color: "#8C8C8C", fontSize: 11, fontWeight: "700" },
  bottomNavLabelActive: { color: "#FF4747", fontWeight: "900" },
  timeline: { marginTop: 16, paddingLeft: 8 },
  timelineItem: { minHeight: 68, flexDirection: "row", position: "relative" },
  dot: { width: 15, height: 15, borderRadius: 8, backgroundColor: "#D9D9D9", marginTop: 2 },
  doneDot: { backgroundColor: "#FF4747" },
  line: { position: "absolute", left: 7, top: 18, width: 2, height: 50, backgroundColor: "#D9D9D9" },
  doneLine: { backgroundColor: "#FF4747" },
  timelineText: { marginLeft: 16, flex: 1 },
  timelineTitle: { color: "#191919", fontSize: 16, fontWeight: "900" },
  timelineMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13 },
});