import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#F5F5F5" },
  content: { flex: 1 },
  launch: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#000000" },
  launchLogo: { width: 260, height: 150, marginBottom: 18 },
  loadingText: { marginTop: 12, color: "#FFFFFF", fontWeight: "700" },
  authBg: { flex: 1, overflow: "hidden", backgroundColor: "#FFF8F1" },
  authBgImage: { opacity: 0.72 },
  authBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(255,248,241,0.28)" },
  authSafe: { flex: 1 },
  authKeyboard: { flex: 1 },
  authScroll: { flexGrow: 1, width: "100%", maxWidth: 540, alignSelf: "center", paddingHorizontal: 20, paddingTop: 24, paddingBottom: 32 },
  authBrand: { alignItems: "center", marginBottom: 18 },
  authLogo: { width: 96, height: 96, borderRadius: 24, backgroundColor: "#000000" },
  authLogoCompact: { width: 76, height: 76, borderRadius: 20 },
  authEyebrow: { marginTop: 10, color: "#55615D", fontSize: 11, lineHeight: 14, fontWeight: "900", letterSpacing: 2.2 },
  authHero: { marginBottom: 14 },
  authPanel: { borderWidth: 1, borderColor: "rgba(226,231,228,0.92)", borderRadius: 24, padding: 20, backgroundColor: "rgba(255,255,255,0.94)", shadowColor: "#17201D", shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.10, shadowRadius: 24, elevation: 5 },
  authTitle: { color: "#17201D", fontSize: 29, lineHeight: 35, fontWeight: "900", letterSpacing: -0.6 },
  authCopy: { marginTop: 10, color: "#66706D", fontSize: 15, lineHeight: 22 },
  authFormCopy: { marginTop: 8, marginBottom: 6, color: "#66706D", fontSize: 14, lineHeight: 21 },
  authFeatureRow: { flexDirection: "row", gap: 8, marginTop: 18 },
  authFeature: { flex: 1, minHeight: 82, alignItems: "center", justifyContent: "center", paddingHorizontal: 6, paddingVertical: 10, borderWidth: 1, borderColor: "#E2E7E4", borderRadius: 16, backgroundColor: "rgba(255,255,255,0.72)" },
  authFeatureIcon: { width: 34, height: 34, alignItems: "center", justifyContent: "center", marginBottom: 6, borderRadius: 17, backgroundColor: "#FFF0EF" },
  authFeatureText: { color: "#35413D", fontSize: 11, lineHeight: 14, fontWeight: "800", textAlign: "center" },
  authNotice: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12, padding: 12, borderRadius: 10, backgroundColor: "#FFFAEB", borderWidth: 1, borderColor: "#FEDF89" },
  authNoticeText: { flex: 1, color: "#B54708", fontSize: 13, fontWeight: "700", lineHeight: 18 },
  authPrimaryButton: { minHeight: 54, borderRadius: 16, paddingHorizontal: 18, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 9, backgroundColor: "#FF4747", borderBottomWidth: 3, borderBottomColor: "#D92F3A" },
  authDivider: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 16 },
  authDividerLine: { flex: 1, height: 1, backgroundColor: "#E7EAE8" },
  authDividerText: { color: "#89918E", fontSize: 11, fontWeight: "700" },
  authInlineMessage: { flexDirection: "row", alignItems: "flex-start", gap: 7, marginTop: 12, padding: 10, borderRadius: 12, backgroundColor: "#F5F7F6" },
  authInlineMessageText: { flex: 1, color: "#667085", fontSize: 12, lineHeight: 17, fontWeight: "600" },
  authEmailButton: { minHeight: 48, marginTop: 10, borderWidth: 1, borderColor: "#DDE2DF", borderRadius: 14, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, backgroundColor: "#F8FAF9" },
  authEmailButtonText: { color: "#202725", fontWeight: "900" },
  authTerms: { marginTop: 14, color: "#909895", fontSize: 10, lineHeight: 15, textAlign: "center" },
  input: { height: 48, marginTop: 12, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, paddingHorizontal: 12, backgroundColor: "#FFFFFF", color: "#191919", fontWeight: "700" },
  passwordWrap: { height: 48, marginTop: 12, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, paddingLeft: 12, paddingRight: 6, backgroundColor: "#FFFFFF", flexDirection: "row", alignItems: "center" },
  passwordInput: { flex: 1, height: "100%", color: "#191919", fontWeight: "700" },
  passwordToggle: { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  gmailButton: { minHeight: 50, borderWidth: 1, borderColor: "#DDE2DF", borderRadius: 14, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, backgroundColor: "#FFFFFF" },
  gmailButtonText: { color: "#191919", fontWeight: "900" },
  textButton: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  textButtonText: { color: "#FF4747", fontWeight: "900" },
  appHeader: { backgroundColor: "#FFFFFF", paddingHorizontal: 14, paddingTop: 8, paddingBottom: 8, borderBottomWidth: 1, borderColor: "#EDEDED" },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  brandLogo: { width: 64, height: 34, borderRadius: 8 },
  brandTitle: { color: "#191919", fontSize: 18, fontWeight: "900" },
  brandSubtitle: { color: "#8C8C8C", fontSize: 12, fontWeight: "700" },
  homeTopRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 8 },
  deliveryRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 2 },
  homeBell: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#EDEDED" },
  search: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 999, paddingHorizontal: 14, height: 38, backgroundColor: "#F5F5F5" },
  searchInput: { flex: 1, color: "#191919", fontWeight: "600" },
  simpleHeaderWrap: { backgroundColor: "#FFFFFF", paddingHorizontal: 14, paddingTop: 8, paddingBottom: 10, borderBottomWidth: 1, borderColor: "#EDEDED" },
  simpleHeaderTitle: { color: "#191919", fontSize: 22, fontWeight: "900" },
  simpleHeaderMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13, fontWeight: "700" },
  kicker: { color: "#8C8C8C", fontSize: 12, fontWeight: "800", textTransform: "uppercase" },
  categoryWrap: { paddingTop: 8, paddingBottom: 4, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderColor: "#EDEDED" },
  categoryList: { paddingHorizontal: 12, gap: 8, paddingBottom: 8 },
  categoryChip: { height: 34, paddingHorizontal: 14, borderRadius: 999, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#E8E8E8", backgroundColor: "#FFFFFF" },
  categoryChipActive: { borderColor: "#FF4747", backgroundColor: "#FFF1F1" },
  categoryText: { color: "#595959", fontWeight: "800", fontSize: 12 },
  categoryTextActive: { color: "#FF4747" },
  emptyText: { padding: 18, color: "#8C8C8C", fontWeight: "800" },
  productList: { paddingHorizontal: 8, paddingTop: 4, paddingBottom: 24 },
  productRow: { gap: 8 },
  screenPad: { padding: 14, paddingBottom: 24 },
  emptyPanel: { alignItems: "center", justifyContent: "center", paddingVertical: 48, gap: 8 },
  emptyPanelTitle: { color: "#191919", fontSize: 20, fontWeight: "900" },
  muted: { marginTop: 8, color: "#8C8C8C", fontSize: 14, lineHeight: 20 },
  cartItemCard: { flexDirection: "row", gap: 12, marginBottom: 10, padding: 12, borderRadius: 12, backgroundColor: "#FFFFFF" },
  cartItemImage: { width: 88, height: 88, borderRadius: 10, backgroundColor: "#F0F0F0" },
  cartItemBody: { flex: 1 },
  cartItemTitle: { color: "#191919", fontSize: 14, fontWeight: "800", lineHeight: 18 },
  price: { color: "#FF4747", fontSize: 15, fontWeight: "900" },
  quantityRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  quantityButton: { width: 42, height: 42, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#D9E0DD" },
  quantityValue: { minWidth: 28, textAlign: "center", color: "#101817", fontSize: 18, fontWeight: "900" },
  panel: { borderRadius: 12, padding: 16, backgroundColor: "#FFFFFF" },
  panelTitle: { marginTop: 4, color: "#191919", fontSize: 20, fontWeight: "900" },
  metric: { marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderColor: "#F0F0F0", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  metricLabel: { color: "#8C8C8C", fontWeight: "700" },
  metricValue: { flexShrink: 1, textAlign: "right", color: "#191919", fontWeight: "900" },
  accentText: { color: "#FF4747" },
  primaryButton: { marginTop: 18, height: 50, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747", borderBottomWidth: 3, borderBottomColor: "#D92F3A" },
  primaryButtonSmall: { flex: 1, minHeight: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747", borderBottomWidth: 3, borderBottomColor: "#D92F3A" },
  primaryButtonText: { color: "#FFFFFF", fontWeight: "900" },
  supportMessageInput: { minHeight: 128, maxHeight: 240, marginTop: 12, borderWidth: 1, borderColor: "#E8E8E8", borderRadius: 10, paddingHorizontal: 12, paddingTop: 14, paddingBottom: 14, backgroundColor: "#FFFFFF", color: "#191919", fontWeight: "700", lineHeight: 21 },
  supportSubmitButton: { marginTop: 18, minHeight: 52, paddingHorizontal: 18, paddingVertical: 13, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747", borderBottomWidth: 3, borderBottomColor: "#D92F3A" },
  supportSubmitButtonText: { flexShrink: 1, color: "#FFFFFF", fontWeight: "900", fontSize: 15, lineHeight: 20, textAlign: "center" },
  actionRow: { marginTop: 10, flexDirection: "row", gap: 10 },
  secondaryButton: { flex: 1, minHeight: 46, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#FFF1F1" },
  secondaryButtonText: { color: "#FF4747", fontWeight: "900" },
  disabled: { opacity: 0.5 },
  accountHero: { flexDirection: "row", alignItems: "center", gap: 14, padding: 16, borderRadius: 12, backgroundColor: "#FFFFFF", marginBottom: 12 },
  accountAvatar: { width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  accountName: { color: "#191919", fontSize: 18, fontWeight: "900" },
  accountMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13, fontWeight: "700" },
  quickLinks: { gap: 10, marginBottom: 12 },
  quickLinkCard: { flexDirection: "row", alignItems: "center", gap: 12, padding: 14, borderRadius: 12, backgroundColor: "#FFFFFF" },
  quickLinkCopy: { flex: 1 },
  quickLinkTitle: { color: "#191919", fontSize: 15, fontWeight: "900" },
  quickLinkMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 12, fontWeight: "700" },
  logoutButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, minHeight: 48, borderRadius: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#FFD6D6" },
  logoutButtonText: { color: "#FF4747", fontWeight: "900" },
  bottomNavWrap: { borderTopWidth: 1, borderColor: "#EDEDED", backgroundColor: "#FFFFFF" },
  bottomNav: { paddingHorizontal: 6, paddingTop: 8, paddingBottom: 4, gap: 4, alignItems: "center" },
  bottomNavItem: { minWidth: 72, alignItems: "center", justifyContent: "center", paddingHorizontal: 8 },
  bottomNavIconWrap: { position: "relative" },
  bottomNavBadge: { position: "absolute", top: -6, right: -10, minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 4, alignItems: "center", justifyContent: "center", backgroundColor: "#FF4747" },
  bottomNavBadgeText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" },
  bottomNavLabel: { marginTop: 4, color: "#8C8C8C", fontSize: 11, fontWeight: "700" },
  bottomNavLabelActive: { color: "#FF4747", fontWeight: "900" },
  timeline: { marginTop: 16, paddingLeft: 8 },
  timelineItem: { minHeight: 68, flexDirection: "row", position: "relative" },
  dot: { width: 15, height: 15, borderRadius: 8, backgroundColor: "#D9D9D9", marginTop: 2 },
  doneDot: { backgroundColor: "#FF4747" },
  line: { position: "absolute", left: 7, top: 18, width: 2, height: 50, backgroundColor: "#D9D9D9" },
  doneLine: { backgroundColor: "#FF4747" },
  timelineText: { marginLeft: 16, flex: 1 },
  timelineTitle: { color: "#191919", fontSize: 16, fontWeight: "900" },
  timelineMeta: { marginTop: 2, color: "#8C8C8C", fontSize: 13 },
});
